// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/video/edit": {
            "post": {
                "description": "提交一个新的视频编辑任务到处理队列",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "提交视频编辑任务",
                "parameters": [
                    {
                        "description": "视频编辑请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VideoEditRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "任务已接受",
                        "schema": {
                            "$ref": "#/definitions/api.VideoEditResponse"
                        }
                    },
                    "400": {
                        "description": "请求格式错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/video/edit/{taskId}": {
            "get": {
                "description": "根据任务ID获取视频编辑任务的当前状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "获取视频编辑任务状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务状态信息",
                        "schema": {
                            "$ref": "#/definitions/api.TaskStatusResponse"
                        }
                    },
                    "404": {
                        "description": "任务未找到",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "根据任务ID取消视频编辑任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "取消视频编辑任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务取消成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.OSSOutput": {
            "type": "object",
            "properties": {
                "accessKey": {
                    "description": "AccessKey 阿里云访问密钥ID",
                    "type": "string"
                },
                "bucket": {
                    "description": "Bucket OSS存储桶名称",
                    "type": "string"
                },
                "endpoint": {
                    "description": "Endpoint OSS服务终端节点",
                    "type": "string"
                },
                "key": {
                    "description": "Key OSS对象键名，即文件在OSS中的路径",
                    "type": "string"
                },
                "secretKey": {
                    "description": "SecretKey 阿里云访问密钥Secret",
                    "type": "string"
                }
            }
        },
        "api.TaskStatusResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "description": "Created 任务创建时间，RFC3339格式",
                    "type": "string"
                },
                "finished": {
                    "description": "Finished 任务完成时间，RFC3339格式",
                    "type": "string"
                },
                "message": {
                    "description": "Message 任务相关的消息或错误信息",
                    "type": "string"
                },
                "outputUrl": {
                    "description": "OutputURL 输出文件的URL地址",
                    "type": "string"
                },
                "progress": {
                    "description": "Progress 任务进度百分比，范围0-1",
                    "type": "number"
                },
                "started": {
                    "description": "Started 任务开始处理时间，RFC3339格式",
                    "type": "string"
                },
                "status": {
                    "description": "Status 任务当前状态，如\"pending\"、\"processing\"、\"completed\"、\"failed\"",
                    "type": "string"
                },
                "taskId": {
                    "description": "TaskID 任务ID",
                    "type": "string"
                }
            }
        },
        "api.VideoEditRequest": {
            "type": "object",
            "properties": {
                "ossOutput": {
                    "description": "OSSOutput 阿里云OSS输出配置，用于将输出文件上传到OSS",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.OSSOutput"
                        }
                    ]
                },
                "outputPath": {
                    "description": "OutputPath 本地输出路径，指定视频文件保存的本地路径",
                    "type": "string"
                },
                "spec": {
                    "description": "Spec 视频编辑规范，包含具体的编辑参数和配置"
                }
            }
        },
        "api.VideoEditResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message 响应消息，提供额外的信息说明",
                    "type": "string"
                },
                "outputUrl": {
                    "description": "OutputURL 输出文件的URL地址（如果已上传到OSS）",
                    "type": "string"
                },
                "status": {
                    "description": "Status 任务状态，如\"accepted\"表示已接受",
                    "type": "string"
                },
                "taskId": {
                    "description": "TaskID 任务ID，用于标识和查询任务状态",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "ffmpeg-go API",
	Description:      "基于FFmpeg的视频编辑服务API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
