// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/video/edit": {
            "post": {
                "description": "提交一个新的视频编辑任务到处理队列",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "提交视频编辑任务",
                "parameters": [
                    {
                        "description": "视频编辑请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VideoEditRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "任务已接受",
                        "schema": {
                            "$ref": "#/definitions/api.VideoEditResponse"
                        }
                    },
                    "400": {
                        "description": "请求格式错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/video/edit/{taskId}": {
            "get": {
                "description": "根据任务ID获取视频编辑任务的当前状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "获取视频编辑任务状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务状态信息",
                        "schema": {
                            "$ref": "#/definitions/api.TaskStatusResponse"
                        }
                    },
                    "404": {
                        "description": "任务未找到",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "根据任务ID取消视频编辑任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "取消视频编辑任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务取消成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.OSSOutput": {
            "type": "object",
            "properties": {
                "accessKey": {
                    "type": "string"
                },
                "bucket": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "secretKey": {
                    "type": "string"
                }
            }
        },
        "api.TaskStatusResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "finished": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "outputUrl": {
                    "type": "string"
                },
                "progress": {
                    "type": "number"
                },
                "started": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "taskId": {
                    "type": "string"
                }
            }
        },
        "api.VideoEditRequest": {
            "type": "object",
            "properties": {
                "ossOutput": {
                    "description": "OSS 输出配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.OSSOutput"
                        }
                    ]
                },
                "outputPath": {
                    "description": "本地输出路径",
                    "type": "string"
                },
                "spec": {}
            }
        },
        "api.VideoEditResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "outputUrl": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "taskId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "ffmpeg-go API",
	Description:      "基于FFmpeg的视频编辑服务API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
