name: Publish Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false

      - name: Fix dependencies
        run: |
          go get github.com/gabriel-vasile/mimetype@latest
          go get github.com/go-playground/validator/v10@v10.20.0
          go get github.com/gin-gonic/gin@v1.10.1
          go get github.com/swaggo/files@v1.0.1
          go get github.com/swaggo/gin-swagger@v1.6.0
          go get github.com/shirou/gopsutil/v3/cpu@v3.24.5
          go get github.com/shirou/gopsutil/v3/disk@v3.24.5
          go mod tidy

      - name: Generate Swagger docs
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g cmd/main.go

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cokefish9527/ffmpeg-go

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDPLATFORM=${{ matrix.platform }}
            TARGETOS=linux
            TARGETARCH=amd64